theme: jekyll-theme-cayman
title: Shonan Meeting No 251 on Green Intelligence
description: Green Intelligence: Sustainable Development and Operations of Intelligent Systems
github:
  is_project_page: false
