theme: jekyll-theme-cayman
title: Shonan Meeting on Green Intelligence
description: NII Shonan Meeting No. 251 | August 31 – September 5, Shonan Village Center, Japan
github:
  is_project_page: false
